dist: bionic
language: python
before_install:
  - sudo apt-get install -y libldap2-dev libsasl2-dev zlib1g-dev make build-essential libssl-dev libbz2-dev libreadline-dev libsqlite3-dev wget llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev liblzma-dev libffi-dev git python3-dateutil ttf-bitstream-vera redis-server nodejs python3-pip libpangocairo-1.0-0 firefox-geckodriver
addons:
  apt:
    update: true
  firefox: latest
services:
  - postgresql
before_script:
  - psql -d 'template1' -c 'CREATE EXTENSION unaccent;' -U postgres
  - psql -c "CREATE DATABASE happyschool;" -U postgres
  - psql -c "CREATE USER happyschool WITH PASSWORD 'libreschool';" -U postgres
  - psql -c "ALTER USER happyschool CREATEDB;" -U postgres
install:
  - pip3 install pipenv
  - pipenv install
  - pipenv install selenium
script:
  - cp happyschool/settings.example.py happyschool/settings.py
  - sed -i 's/DEBUG = False/DEBUG = True/g' happyschool/settings.py
  - pipenv run ./manage.py makemigrations && pipenv run ./manage.py migrate
  - npm install
  - npx eslint --ext .js,.vue assets/
  - ./node_modules/.bin/webpack --config webpack.prod.js
  - pipenv run coverage run --source='.' manage.py test
  - pipenv run coverage report
